<?php

/*
|--------------------------------------------------------------------------
| Component Showcase Registry
|--------------------------------------------------------------------------
|
| Central catalog for the internal Blade + Alpine component showcase
| (/components, admin only). Every reusable component that the current
| architecture supports is listed here with a STABLE machine id
| (card-01, table-01, chart-01 …). See CLAUDE.md → "Component showcase".
|
| Rules:
|  - IDs are permanent. Never renumber an existing component; new ones get
|    the next free number in their category. IDs must NOT be derived from
|    array position — the explicit 'id' key is the source of truth.
|  - Numbering is independent per category.
|  - Only current Blade + Alpine components belong here (no React/Inertia,
|    no unlocalized template-demo leftovers). Gaps are documented, not faked.
|  - Each component's live preview is rendered by its REAL implementation
|    via resources/views/components/showcase/example.blade.php (keyed on id),
|    with safe mock data supplied by ShowcaseController — never DB fixtures.
|
*/

return [

    // Ordered category metadata. 'noun' drives the Persian reference phrase
    // shown for each component, e.g. «کارت شماره ۱».
    'categories' => [
        'tokens' => ['title' => 'توکن‌های طراحی', 'noun' => 'توکن', 'icon' => 'ui-elements'],
        'kpi' => ['title' => 'کارت‌های شاخص (KPI)', 'noun' => 'شاخص', 'icon' => 'charts'],
        'cards' => ['title' => 'کارت‌ها', 'noun' => 'کارت', 'icon' => 'grid'],
        'tables' => ['title' => 'جدول‌ها', 'noun' => 'جدول', 'icon' => 'tables'],
        'charts' => ['title' => 'نمودارها', 'noun' => 'نمودار', 'icon' => 'charts'],
        'forms' => ['title' => 'فرم‌ها', 'noun' => 'فرم', 'icon' => 'forms'],
        'buttons' => ['title' => 'دکمه‌ها و عملیات', 'noun' => 'دکمه', 'icon' => 'ui-elements'],
        'badges' => ['title' => 'نشان‌ها و وضعیت‌ها', 'noun' => 'نشان', 'icon' => 'ui-elements'],
        'financial' => ['title' => 'اجزای مالی', 'noun' => 'جزء مالی', 'icon' => 'scale-balance'],
        'widgets' => ['title' => 'ویجت‌های داشبورد', 'noun' => 'ویجت', 'icon' => 'dashboard'],
        'todo' => ['title' => 'کارها و یادآورها', 'noun' => 'کار', 'icon' => 'task'],
        'filters' => ['title' => 'فیلترها', 'noun' => 'فیلتر', 'icon' => 'forms'],
        'alerts' => ['title' => 'اعلان‌ها', 'noun' => 'اعلان', 'icon' => 'bell'],
        'modals' => ['title' => 'مودال‌ها و منوها', 'noun' => 'مودال', 'icon' => 'ui-elements'],
        'navigation' => ['title' => 'اجزای ناوبری', 'noun' => 'ناوبری', 'icon' => 'pages'],
        'states' => ['title' => 'وضعیت‌های خالی و بارگذاری', 'noun' => 'وضعیت', 'icon' => 'task'],
    ],

    'components' => [

        // ---- Design tokens (Phase 2 foundation) ------------------------
        [
            'id' => 'token-01',
            'tech' => 'financial-color-tokens',
            'category' => 'tokens',
            'name' => 'رنگ‌های مالی',
            'component' => 'text-profit / text-loss / text-trend-up …',
            'source' => 'resources/css/tailadmin.css',
            'description' => 'توکن‌های معنایی سود/زیان/درآمد/هزینه و روند. زیر .dark بازتعریف می‌شوند، پس بدون کلاس dark: هم در تم تاریک درست‌اند.',
            'variants' => ['profit', 'loss', 'income', 'expense', 'trend-up', 'trend-down'],
        ],
        [
            'id' => 'token-02',
            'tech' => 'status-color-tokens',
            'category' => 'tokens',
            'name' => 'رنگ‌های وضعیت',
            'component' => '<x-ui.status status="completed" />',
            'source' => 'app/Support/Design/StatusPresenter.php',
            'description' => 'نُه وضعیت استاندارد با نگاشت واحد (StatusPresenter). همیشه نقطهٔ رنگی + برچسب متنی — هرگز فقط رنگ.',
            'variants' => ['draft', 'pending', 'processing', 'approved', 'completed', 'cancelled', 'failed', 'needs_review', 'archived'],
        ],
        [
            'id' => 'token-03',
            'tech' => 'radius-shadow-density-tokens',
            'category' => 'tokens',
            'name' => 'شعاع، سایه و تراکم',
            'component' => 'rounded-card / shadow-card / --height-chart-md',
            'source' => 'resources/css/tailadmin.css',
            'description' => 'توکن‌های شعاع گوشه، ارتفاع سایه، ارتفاع نمودار و ارتفاع ردیف جدول که کل سیستم گزارش‌گیری از آن‌ها تغذیه می‌کند.',
            'variants' => ['radius-card', 'radius-control', 'shadow-card', 'shadow-dropdown', 'chart heights'],
        ],

        // ---- KPI cards -------------------------------------------------
        [
            'id' => 'kpi-01',
            'tech' => 'kpi-card',
            'category' => 'kpi',
            'name' => 'کارت شاخص',
            'component' => '<x-kpi.card label value change :sparkline />',
            'source' => 'resources/views/components/kpi/card.blade.php',
            'description' => 'کارت شاخص کلیدی با مقدار (ارقام هم‌تراز)، درصد تغییر با فلش و علامت، اسپارک‌لاین، نوار پیشرفت و نشان وضعیت.',
            'variants' => ['statistic', 'financial', 'goal', 'warning', 'با اسپارک‌لاین'],
        ],

        // ---- Cards ----------------------------------------------------
        [
            'id' => 'card-01',
            'tech' => 'component-card',
            'category' => 'cards',
            'name' => 'کارت پایه',
            'component' => '<x-common.component-card title desc>',
            'source' => 'resources/views/components/common/component-card.blade.php',
            'description' => 'کارت استاندارد با سربرگ (عنوان + توضیح اختیاری) و بدنه اسلات‌دار؛ ظرف پایه بیشتر بخش‌های صفحات.',
            'variants' => ['با توضیح', 'بدون توضیح'],
        ],
        [
            'id' => 'card-02',
            'tech' => 'ecommerce-metrics',
            'category' => 'cards',
            'name' => 'کارت شاخص کلیدی (KPI)',
            'component' => '<x-ecommerce.ecommerce-metrics :kpis :canSeeFinancials>',
            'source' => 'resources/views/components/ecommerce/ecommerce-metrics.blade.php',
            'description' => 'شبکه کارت‌های شاخص داشبورد (مشتریان جدید، فروش ناخالص، موجودی) با درصد تغییر نسبت به ماه قبل.',
            'variants' => ['با دسترسی مالی', 'بدون دسترسی مالی'],
        ],
        [
            'id' => 'card-03',
            'tech' => 'capability-list',
            'category' => 'cards',
            'name' => 'کارت فهرست قابلیت‌ها',
            'component' => '<x-common.capability-list :available :future :missing>',
            'source' => 'resources/views/components/common/capability-list.blade.php',
            'description' => 'فهرست وضعیت قابلیت‌ها در سه گروه (موجود، آینده، ناموجود) با نشان رنگی؛ در صفحات ابزار استفاده می‌شود.',
            'variants' => ['موجود', 'آینده', 'ناموجود'],
        ],

        // ---- Tables ---------------------------------------------------
        [
            'id' => 'table-01',
            'tech' => 'data-table',
            'category' => 'tables',
            'name' => 'جدول داده استاندارد',
            'component' => '<x-tables.data-table :headers :paginator :totals>',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'جدول کارتی به سبک shadcn: سرستون‌های قابل مرتب‌سازی، ستون‌های قابل نمایش/پنهان، ردیف جمع اختیاری و پیام خالی.',
            'variants' => ['ساده', 'با ردیف جمع', 'خالی'],
        ],
        [
            'id' => 'table-02',
            'tech' => 'pro-table',
            'category' => 'tables',
            'name' => 'جدول حرفه‌ای با نوار ابزار',
            'component' => '<x-tables.pro-table :columns :searchName ...>',
            'source' => 'resources/views/components/tables/pro-table.blade.php',
            'description' => 'پوسته فهرست کامل: جستجو + بازه تاریخ شمسی + کنترل نمایش ستون‌ها روی data-table، همه با فرم GET و بارگذاری کامل صفحه.',
            'variants' => ['با جستجو', 'با بازه تاریخ', 'با کنترل ستون'],
        ],
        [
            'id' => 'table-03',
            'tech' => 'recent-orders',
            'category' => 'tables',
            'name' => 'جدول سفارش‌های اخیر',
            'component' => '<x-ecommerce.recent-orders :orders>',
            'source' => 'resources/views/components/ecommerce/recent-orders.blade.php',
            'description' => 'جدول فشرده داشبورد برای آخرین سفارش‌ها با نشان وضعیت و لینک مشاهده بیشتر.',
            'variants' => ['با داده', 'خالی'],
        ],

        [
            'id' => 'table-04',
            'tech' => 'num-cell',
            'category' => 'tables',
            'name' => 'سلول عددی / مالی',
            'component' => '<x-tables.num :value :signed unit />',
            'source' => 'resources/views/components/tables/num.blade.php',
            'description' => 'واحد پایهٔ هر عدد پولی. dir=ltr برای رقم و علامت منفی، راست‌چین برای هم‌ترازی با هدر، و ارقام هم‌عرض تا مبالغ زیر هم بنشینند. با signed رنگ سود/زیان و علامت +/- می‌گیرد.',
            'variants' => ['ساده', 'signed (سود/زیان)', 'با واحد', 'خالی (—)'],
        ],
        [
            'id' => 'table-05',
            'tech' => 'pro-table-bulk',
            'category' => 'tables',
            'name' => 'جدول با انتخاب ردیف و عملیات گروهی',
            'component' => '<x-tables.pro-table> + :bulkActions',
            'source' => 'resources/views/components/tables/pro-table.blade.php',
            'description' => 'انتخاب ردیف (با حالت نامعین در هدر)، نوار عملیات گروهی، حالت‌های تراکم (فشرده/پیش‌فرض/راحت)، هدر چسبان و بازگرداندن ستون‌ها به پیش‌فرض.',
            'variants' => ['انتخاب ردیف', 'عملیات گروهی', 'تراکم', 'هدر چسبان'],
        ],

        // ---- Charts (ApexCharts, هر کدام شناسه یکتا) -------------------
        [
            'id' => 'chart-01',
            'tech' => 'monthly-sale',
            'category' => 'charts',
            'name' => 'نمودار سفارش‌های ماهانه',
            'component' => '<x-ecommerce.monthly-sale :categories :series>',
            'source' => 'resources/views/components/ecommerce/monthly-sale.blade.php',
            'description' => 'ویجت داشبورد که روی پرست bar سوار است. داده را از سرور می‌گیرد و شناسهٔ المان خودکار تولید می‌شود (دیگر شناسهٔ ثابت ندارد).',
            'variants' => ['میله‌ای', 'داده پویا از سرور'],
        ],
        [
            'id' => 'chart-02',
            'tech' => 'monthly-target',
            'category' => 'charts',
            'name' => 'نمودار هدف ماهانه',
            'component' => '<x-ecommerce.monthly-target />',
            'source' => 'resources/views/components/ecommerce/monthly-target.blade.php',
            'description' => 'گیج رادیال تحقق هدف ماه، سوار بر پرست radial. هنوز به دادهٔ واقعی وصل نیست.',
            'variants' => ['رادیال / گیج'],
        ],
        [
            'id' => 'chart-03',
            'tech' => 'statistics-chart',
            'category' => 'charts',
            'name' => 'نمودار آماری فروش و درآمد',
            'component' => '<x-ecommerce.statistics-chart />',
            'source' => 'resources/views/components/ecommerce/statistics-chart.blade.php',
            'description' => 'نمودار ناحیه‌ای فروش/درآمد با کلید بازه و انتخاب‌گر تاریخ، سوار بر پرست area. هنوز به دادهٔ واقعی وصل نیست.',
            'variants' => ['ناحیه‌ای', 'چند سری'],
        ],

        [
            'id' => 'chart-04',
            'tech' => 'chart-preset',
            'category' => 'charts',
            'name' => 'نمودار پرست‌محور (بدون شناسه ثابت)',
            'component' => '<x-charts.chart preset :series :categories />',
            'source' => 'resources/views/components/charts/chart.blade.php',
            'description' => 'واحد پایهٔ همهٔ نمودارها. شناسهٔ المان خودکار تولید می‌شود، پس یک پرست را می‌توان چند بار در یک صفحه استفاده کرد. RTL، ارقام فارسی و تم تاریک به‌صورت مرکزی اعمال می‌شوند.',
            'variants' => ['line', 'area', 'bar', 'bar-horizontal', 'bar-stacked', 'donut', 'pie', 'mixed', 'waterfall', 'heatmap', 'radial', 'kpi-trend', 'comparison'],
        ],
        [
            'id' => 'chart-05',
            'tech' => 'donut-horizontal-bar',
            'category' => 'charts',
            'name' => 'نمودار دایره‌ای و افقی',
            'component' => '<x-charts.chart preset="donut|bar-horizontal" />',
            'source' => 'resources/js/tailadmin/charts/presets.js',
            'description' => 'پرست‌های تفکیک سهم (دونات) و مقایسهٔ دسته‌ها (میله افقی) — مناسب تفکیک هزینه و عملکرد کانال‌ها.',
            'variants' => ['donut', 'bar-horizontal'],
        ],

        // ---- Forms ----------------------------------------------------
        [
            'id' => 'form-01',
            'tech' => 'date-picker',
            'category' => 'forms',
            'name' => 'انتخاب‌گر تاریخ',
            'component' => '<x-form.date-picker name label>',
            'source' => 'resources/views/components/form/date-picker.blade.php',
            'description' => 'ورودی تاریخ مبتنی بر Flatpickr با برچسب و آیکن تقویم.',
            'variants' => ['تک‌تاریخ'],
        ],
        [
            'id' => 'form-02',
            'tech' => 'jalali-date-range',
            'category' => 'forms',
            'name' => 'بازه تاریخ شمسی',
            'component' => '<x-form.jalali-date-range :fromName :toName>',
            'source' => 'resources/views/components/form/jalali-date-range.blade.php',
            'description' => 'انتخاب بازه تاریخ جلالی (کتابخانه vanilla jalalidatepicker) که مقدار میلادی را در فیلدهای مخفی برای سرور می‌گذارد.',
            'variants' => ['بازه از/تا'],
        ],
        [
            'id' => 'form-03',
            'tech' => 'filter-bar',
            'category' => 'forms',
            'name' => 'نوار فیلتر',
            'component' => '<x-common.filter-bar :action :except>',
            'source' => 'resources/views/components/common/filter-bar.blade.php',
            'description' => 'فرم GET که پارامترهای فعال دیگر را حفظ می‌کند؛ هر تغییر فیلتر یک بارگذاری کامل صفحه است (بدون AJAX).',
            'variants' => ['GET با حفظ پارامترها'],
        ],
        [
            'id' => 'form-04',
            'tech' => 'toman-input',
            'category' => 'forms',
            'name' => 'ورودی مبلغ تومان',
            'component' => 'formatTomanInput(el, hiddenSelector)',
            'source' => 'resources/js/tailadmin/app.js',
            'description' => 'ورودی مبلغ با جداکننده هزارگان هنگام تایپ که مقدار خام عددی را در یک فیلد مخفی برای سرور نگه می‌دارد.',
            'variants' => ['جداکننده هزارگان + فیلد مخفی'],
        ],

        // ---- Buttons & actions ---------------------------------------
        [
            'id' => 'button-01',
            'tech' => 'button',
            'category' => 'buttons',
            'name' => 'دکمه',
            'component' => '<x-ui.button variant size>',
            'source' => 'resources/views/components/ui/button.blade.php',
            'description' => 'دکمه پایه با گونه‌های primary و outline، اندازه‌های sm و md، آیکن ابتدا/انتها و حالت غیرفعال.',
            'variants' => ['primary', 'outline', 'sm', 'md', 'disabled'],
        ],
        [
            'id' => 'button-02',
            'tech' => 'dropdown-menu',
            'category' => 'buttons',
            'name' => 'منوی عملیات کشویی',
            'component' => '<x-common.dropdown-menu :items>',
            'source' => 'resources/views/components/common/dropdown-menu.blade.php',
            'description' => 'دکمه سه‌نقطه با منوی کشویی Alpine برای عملیات؛ روی کارت‌ها و ویجت‌ها استفاده می‌شود.',
            'variants' => ['فهرست دلخواه'],
        ],

        // ---- Badges & status -----------------------------------------
        [
            'id' => 'badge-01',
            'tech' => 'badge',
            'category' => 'badges',
            'name' => 'نشان پایه',
            'component' => '<x-ui.badge variant color size>',
            'source' => 'resources/views/components/ui/badge.blade.php',
            'description' => 'نشان رنگی با گونه‌های light و solid و رنگ‌های معنایی (primary/success/error/warning/info/…) و اندازه sm/md.',
            'variants' => ['light', 'solid', 'success', 'error', 'warning', 'info'],
        ],
        [
            'id' => 'badge-02',
            'tech' => 'order-status-badge',
            'category' => 'badges',
            'name' => 'نشان وضعیت سفارش',
            'component' => '<x-orders.status-badge type value>',
            'source' => 'resources/views/components/orders/status-badge.blade.php',
            'description' => 'نشان وضعیت با نگاشت برچسب/رنگ فارسی برای وضعیت سفارش، مالی، سود و پرداخت؛ مقدار ناشناخته امن نمایش داده می‌شود.',
            'variants' => ['order', 'financial', 'profit', 'payment'],
        ],
        [
            'id' => 'badge-03',
            'tech' => 'report-state-badge',
            'category' => 'badges',
            'name' => 'نشان وضعیت گزارش',
            'component' => '<x-reports.state-badge state>',
            'source' => 'resources/views/components/reports/state-badge.blade.php',
            'description' => 'نشان وضعیت گزارش دوره‌ای (پیش‌نویس، نیازمند بازبینی، نهایی، تعدیل‌شده) با رنگ متناظر.',
            'variants' => ['draft', 'needs_review', 'final', 'adjusted'],
        ],
        [
            'id' => 'badge-04',
            'tech' => 'avatar',
            'category' => 'badges',
            'name' => 'آواتار',
            'component' => '<x-ui.avatar size status>',
            'source' => 'resources/views/components/ui/avatar.blade.php',
            'description' => 'آواتار کاربر با اندازه‌های مختلف و نشانگر وضعیت (آنلاین/آفلاین/مشغول).',
            'variants' => ['online', 'offline', 'busy', 'اندازه‌های مختلف'],
        ],

        [
            'id' => 'badge-05',
            'tech' => 'status-badge',
            'category' => 'badges',
            'name' => 'نشان وضعیت استاندارد',
            'component' => '<x-ui.status status="completed" />',
            'source' => 'resources/views/components/ui/status.blade.php',
            'description' => 'نشان وضعیت سیستم طراحی؛ از StatusPresenter می‌خواند تا یک وضعیت هرگز دو جور رندر نشود. نقطهٔ رنگی + برچسب (نه فقط رنگ).',
            'variants' => ['۹ وضعیت استاندارد'],
        ],

        // ---- Alerts ---------------------------------------------------
        [
            'id' => 'alert-01',
            'tech' => 'alert',
            'category' => 'alerts',
            'name' => 'هشدار',
            'component' => '<x-ui.alert variant title message>',
            'source' => 'resources/views/components/ui/alert.blade.php',
            'description' => 'کادر هشدار با گونه‌های success/error/warning/info، آیکن، عنوان، پیام و اسلات محتوای دلخواه.',
            'variants' => ['success', 'error', 'warning', 'info'],
        ],

        // ---- Modals & menus ------------------------------------------
        [
            'id' => 'modal-01',
            'tech' => 'modal',
            'category' => 'modals',
            'name' => 'مودال پایه',
            'component' => '<x-ui.modal :isOpen :showCloseButton>',
            'source' => 'resources/views/components/ui/modal.blade.php',
            'description' => 'مودال Alpine با پس‌زمینه تار، بستن با Escape/کلیک بیرون و اسلات محتوا؛ باز/بسته با رویداد یا x-data کنترل می‌شود.',
            'variants' => ['با دکمه بستن', 'بدون دکمه بستن'],
        ],
        [
            'id' => 'modal-02',
            'tech' => 'table-dropdown',
            'category' => 'modals',
            'name' => 'منوی عملیات ردیف',
            'component' => '<x-common.table-dropdown :items>',
            'source' => 'resources/views/components/common/table-dropdown.blade.php',
            'description' => 'منوی سه‌نقطه ردیف جدول که به سمت جهت خواندنِ دارای فضا باز می‌شود.',
            'variants' => ['فهرست عملیات'],
        ],

        // ---- Navigation ----------------------------------------------
        [
            'id' => 'nav-01',
            'tech' => 'page-breadcrumb',
            'category' => 'navigation',
            'name' => 'مسیر راهنما (بردکرامب)',
            'component' => '<x-common.page-breadcrumb pageTitle parentLabel parentUrl>',
            'source' => 'resources/views/components/common/page-breadcrumb.blade.php',
            'description' => 'سربرگ صفحه با مسیر راهنما (خانه ← والد ← صفحه) و عنوان بزرگ صفحه.',
            'variants' => ['بدون والد', 'با والد'],
        ],
        [
            'id' => 'nav-02',
            'tech' => 'theme-toggle',
            'category' => 'navigation',
            'name' => 'کلید تغییر پوسته',
            'component' => '<x-common.theme-toggle />',
            'source' => 'resources/views/components/common/theme-toggle.blade.php',
            'description' => 'دکمه تغییر حالت روشن/تاریک که انتخاب را در localStorage نگه می‌دارد.',
            'variants' => ['روشن/تاریک'],
        ],

        // ---- Empty & loading states ----------------------------------
        [
            'id' => 'state-01',
            'tech' => 'empty-table-state',
            'category' => 'states',
            'name' => 'وضعیت خالی',
            'component' => '<x-tables.data-table emptyMessage>',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'حالت «موردی یافت نشد» جدول داده وقتی هیچ ردیفی وجود ندارد.',
            'variants' => ['پیام خالی سفارشی'],
        ],
        [
            'id' => 'state-02',
            'tech' => 'preloader',
            'category' => 'states',
            'name' => 'بارگذاری (اسپینر)',
            'component' => '<x-common.preloader />',
            'source' => 'resources/views/components/common/preloader.blade.php',
            'description' => 'اسپینر چرخان برند برای حالت بارگذاری؛ نسخه واقعی یک پوشش تمام‌صفحه است (اینجا در قاب نمونه نشان داده می‌شود).',
            'variants' => ['اسپینر چرخان'],
        ],
        [
            'id' => 'state-03',
            'tech' => 'data-states',
            'category' => 'states',
            'name' => 'وضعیت‌های استاندارد داده',
            'component' => '<x-states.state variant="empty|no-results|error|permission|loading|skeleton" />',
            'source' => 'resources/views/components/states/state.blade.php',
            'description' => 'یک واحد برای همهٔ حالت‌های دادهٔ خالی/بدون‌نتیجه/خطا/عدم‌دسترسی/بارگذاری/اسکلتون با متن فارسی پیش‌فرض و آیکن SVG. اسکلتون ارتفاع را رزرو می‌کند تا چیدمان نپرد.',
            'variants' => ['empty', 'no-results', 'error', 'permission', 'loading', 'skeleton'],
        ],
        [
            'id' => 'table-06',
            'tech' => 'financial-grouped-table',
            'category' => 'tables',
            'name' => 'جدول مالی چندسطحی',
            'component' => '<x-tables.data-table> + <x-tables.num>',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'گروه‌بندی سطرها با سرگروه و جمع هر گروه؛ همه مبالغ از <x-tables.num> عبور می‌کنند تا ارقام هم‌تراز بمانند.',
            'variants' => ['گروه‌بندی', 'جمع گروه', 'جمع کل'],
            'usage' => 'برای صورت سود و زیان و تفکیک حساب‌ها.',
        ],
        [
            'id' => 'table-07',
            'tech' => 'period-comparison-table',
            'category' => 'tables',
            'name' => 'جدول مقایسه دوره',
            'component' => '<x-tables.data-table> + <x-tables.num signed>',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'مقایسه دو دوره کنار هم با ستون تغییر (درصد و مبلغ) که با علامت و رنگ سود/زیان نمایش داده می‌شود.',
            'variants' => ['این دوره / دوره قبل', 'ستون تغییر', 'درصد'],
            'usage' => 'برای گزارش ماه جاری در برابر ماه قبل.',
        ],
        [
            'id' => 'table-08',
            'tech' => 'ranking-table',
            'category' => 'tables',
            'name' => 'جدول رتبه‌بندی',
            'component' => '<x-tables.data-table> + rank badge',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'فهرست رتبه‌دار با شماره رتبه، سهم درصدی و مبلغ؛ برای پرفروش‌ترین‌ها.',
            'variants' => ['رتبه', 'سهم درصدی', 'مبلغ'],
            'usage' => 'برای پرفروش‌ترین محصولات/مشتریان در قالب جدول کامل.',
        ],
        [
            'id' => 'table-09',
            'tech' => 'drill-down-table',
            'category' => 'tables',
            'name' => 'جدول کشویی (Drill-down)',
            'component' => '<x-tables.data-table> + Alpine row expand',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'هر سطر با کلیک باز می‌شود و جزئیات زیرمجموعه را نشان می‌دهد. باز/بسته شدن فقط Alpine است؛ داده از قبل رندر شده.',
            'variants' => ['سطر بازشونده', 'جزئیات تودرتو'],
            'usage' => 'برای دیدن اقلام یک فاکتور بدون ترک صفحه.',
        ],
        [
            'id' => 'table-10',
            'tech' => 'due-date-table',
            'category' => 'tables',
            'name' => 'جدول سررسید و وضعیت مالی',
            'component' => '<x-tables.data-table> + <x-ui.status>',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'سررسیدهای شمسی با نشان وضعیت و برجسته‌سازی معوق‌ها (متن + رنگ، نه فقط رنگ).',
            'variants' => ['سررسید', 'معوق', 'وضعیت'],
            'usage' => 'برای مطالبات، چک‌ها و اقساط.',
        ],
        [
            'id' => 'table-11',
            'tech' => 'audit-log-table',
            'category' => 'tables',
            'name' => 'جدول لاگ حسابرسی',
            'component' => '<x-tables.data-table> + <x-ui.status>',
            'source' => 'resources/views/components/tables/data-table.blade.php',
            'description' => 'ردیف‌های تغییر با کاربر، زمان شمسی، مقدار قبل/بعد و وضعیت — فقط‌خواندنی.',
            'variants' => ['کاربر', 'زمان', 'قبل/بعد'],
            'usage' => 'برای ردیابی تغییرات مالی؛ مقادیر عددی از <x-tables.num> می‌آیند.',
            'limitations' => 'بدون بک‌اند اختصاصی؛ داده از لاگ فعالیت می‌آید.',
        ],
        [
            'id' => 'chart-06',
            'tech' => 'cumulative-target-chart',
            'category' => 'charts',
            'name' => 'نمودار تجمعی محقق‌شده در برابر هدف',
            'component' => '<x-charts.chart preset="cumulative-target">',
            'source' => 'resources/js/tailadmin/charts/presets.js',
            'description' => 'پرست خودش مقادیر دوره‌ای را تجمعی می‌کند؛ خط هدف نقطه‌چین است تا از محقق‌شده متمایز بماند.',
            'variants' => ['تجمعی', 'هدف نقطه‌چین'],
            'usage' => 'برای پیشرفت فروش نسبت به هدف ماه.',
        ],
        [
            'id' => 'chart-07',
            'tech' => 'revenue-orders-chart',
            'category' => 'charts',
            'name' => 'نمودار درآمد و تعداد سفارش',
            'component' => '<x-charts.chart preset="revenue-orders">',
            'source' => 'resources/js/tailadmin/charts/presets.js',
            'description' => 'درآمد (میله) و تعداد سفارش (خط) روی دو محور مستقل — بدون محور دوم، تعداد سفارش در برابر مبالغ تومانی صاف می‌شد.',
            'variants' => ['دو محوره', 'میله + خط'],
            'usage' => 'برای دیدن همزمان حجم و ارزش فروش.',
        ],
        [
            'id' => 'chart-08',
            'tech' => 'pnl-bridge-chart',
            'category' => 'charts',
            'name' => 'پل سود و زیان',
            'component' => '<x-charts.chart preset="pnl-bridge">',
            'source' => 'resources/js/tailadmin/charts/presets.js',
            'description' => 'آبشار سود ناخالص تا خالص؛ گام‌های مثبت با توکن سود و منفی با توکن زیان رنگ می‌گیرند و میله پایانی خالص است.',
            'variants' => ['آبشار', 'رنگ سود/زیان', 'میله خالص'],
            'usage' => 'برای توضیح اینکه سود ناخالص چطور به خالص رسید.',
        ],
        [
            'id' => 'fin-01',
            'tech' => 'financial-summary',
            'category' => 'financial',
            'name' => 'کارت خلاصه مالی',
            'component' => '<x-financial.summary :rows :total>',
            'source' => 'resources/views/components/financial/summary.blade.php',
            'description' => 'یک کامپوننت پشت همه خلاصه‌های مالی: سود، جریان نقدی، مطالبات، بدهی‌ها، وام، چک، مالیات و بستن ماه. سطر برچسب→عدد با جمع برجسته.',
            'variants' => ['سود', 'جریان نقدی', 'مطالبات', 'بدهی‌ها', 'وام و چک', 'مالیات', 'بستن ماه'],
            'usage' => 'با props داده بدهید؛ منطق کسب‌وکار در ویو نیست.',
        ],
        [
            'id' => 'fin-02',
            'tech' => 'financial-breakdown',
            'category' => 'financial',
            'name' => 'تفکیک درآمد و هزینه',
            'component' => '<x-financial.breakdown :items>',
            'source' => 'resources/views/components/financial/breakdown.blade.php',
            'description' => 'نمودار دونات/میله افقی به همراه جدول سهم و مبلغ. جدول اختیاری نیست: نمودار به‌تنهایی برای صفحه‌خوان قابل خواندن نیست.',
            'variants' => ['دونات', 'میله افقی', 'سهم درصدی'],
            'usage' => 'برای تفکیک درآمد بر اساس کانال یا هزینه بر اساس دسته.',
        ],
        [
            'id' => 'fin-03',
            'tech' => 'financial-bridge',
            'category' => 'financial',
            'name' => 'پل سود ناخالص تا خالص',
            'component' => '<x-financial.bridge :steps>',
            'source' => 'resources/views/components/financial/bridge.blade.php',
            'description' => 'آبشار گام‌به‌گام از سود ناخالص تا خالص، به همراه جدول معادل همان اعداد.',
            'variants' => ['آبشار', 'جدول معادل'],
            'usage' => 'برای گزارش دوره‌ای شرکا.',
        ],
        [
            'id' => 'wid-01',
            'tech' => 'ranked-list',
            'category' => 'widgets',
            'name' => 'فهرست رتبه‌بندی‌شده',
            'component' => '<x-widgets.ranked-list :items>',
            'source' => 'resources/views/components/widgets/ranked-list.blade.php',
            'description' => 'یک کامپوننت پشت همه ویجت‌های «برترین‌ها»: محصولات، مشتریان، دسته‌ها، کانال‌ها و جدول امتیازات. نوار نسبی پشت هر سطر.',
            'variants' => ['برترین محصولات', 'برترین مشتریان', 'کانال‌ها', 'جدول امتیازات'],
            'usage' => 'با props داده بدهید؛ کامپوننت به دیتابیس دست نمی‌زند.',
        ],
        [
            'id' => 'wid-02',
            'tech' => 'timeline',
            'category' => 'widgets',
            'name' => 'خط زمانی و فعالیت‌ها',
            'component' => '<x-widgets.timeline :items>',
            'source' => 'resources/views/components/widgets/timeline.blade.php',
            'description' => 'ریل عمودی رویدادها با نقطه رنگی و زمان شمسی — پشت فعالیت‌های اخیر، خط زمانی و اعلان‌ها.',
            'variants' => ['فعالیت اخیر', 'اعلان‌ها', 'خط زمانی'],
            'usage' => 'تاریخ‌ها را از قبل شمسی‌شده بفرستید؛ منطق تاریخ در ویو نیست.',
        ],
        [
            'id' => 'wid-03',
            'tech' => 'quick-stats',
            'category' => 'widgets',
            'name' => 'آمار سریع',
            'component' => '<x-widgets.quick-stats :stats>',
            'source' => 'resources/views/components/widgets/quick-stats.blade.php',
            'description' => 'نوار فشرده اعداد کلیدی که از <x-kpi.compact> استفاده می‌کند تا تایپوگرافی و فلش روند با کارت‌های KPI یکی بماند.',
            'variants' => ['۲ تا ۵ ستون', 'با درصد تغییر'],
            'usage' => 'بالای صفحات گزارش، به‌عنوان جمع‌بندی یک‌خطی.',
        ],
        [
            'id' => 'wid-04',
            'tech' => 'target-progress',
            'category' => 'widgets',
            'name' => 'پیشرفت هدف فروش',
            'component' => '<x-widgets.target-progress :actual :target>',
            'source' => 'resources/views/components/widgets/target-progress.blade.php',
            'description' => 'گیج رادیال + اعداد دقیق (محقق‌شده/هدف/باقی‌مانده) و نمودار تجمعی اختیاری.',
            'variants' => ['گیج', 'اعداد دقیق', 'نمودار تجمعی'],
            'usage' => 'برای داشبورد مدیریتی.',
        ],
        [
            'id' => 'todo-01',
            'tech' => 'todo-list',
            'category' => 'todo',
            'name' => 'فهرست کارها',
            'component' => '<x-todo.list :items :interactive>',
            'source' => 'resources/views/components/todo/list.blade.php',
            'description' => 'یک کامپوننت پشت کارت کار، چک‌لیست، یادآور و کارهای پیش‌رو/معوق. اولویت (نقطه+متن)، سررسید شمسی، وضعیت، نوار پیشرفت و حالت معوق.',
            'variants' => ['تعاملی', 'فقط‌خواندنی', 'چک‌لیست پیشرفت', 'معوق', 'خالی'],
            'usage' => 'قرارداد آیتم در بالای فایل مستند شده؛ بعداً می‌توان بدون تغییر ظاهر به بک‌اند وصلش کرد.',
            'limitations' => 'بک‌اند کار وجود ندارد؛ تیک زدن فقط در Alpine و محلی است.',
        ],
        [
            'id' => 'filter-01',
            'tech' => 'filter-chips',
            'category' => 'filters',
            'name' => 'چیپ‌های فیلتر فعال',
            'component' => '<x-filters.chips :filters :clearUrl>',
            'source' => 'resources/views/components/filters/chips.blade.php',
            'description' => 'نشان می‌دهد چه چیزی نتایج را محدود کرده و هر کدام را جداگانه حذف می‌کند. آدرس هر چیپ از TableQuery می‌آید، پس حذف یک فیلتر مرتب‌سازی و بقیه فیلترها را از بین نمی‌برد.',
            'variants' => ['حذف تکی', 'پاک کردن همه'],
            'usage' => 'بالای هر جدول سرور-محور.',
        ],
        [
            'id' => 'filter-02',
            'tech' => 'filter-panel',
            'category' => 'filters',
            'name' => 'پنل فیلتر پیشرفته',
            'component' => '<x-filters.panel>',
            'source' => 'resources/views/components/filters/panel.blade.php',
            'description' => 'پنل بازشونده با فرم GET؛ هر فیلتر یک پارامتر URL است پس نتیجه قابل اشتراک و دکمه بازگشت سالم است. باز/بسته بودن در localStorage می‌ماند.',
            'variants' => ['بازشونده', 'شمارنده فیلتر فعال', 'GET'],
            'usage' => 'برای گزارش‌هایی با فیلترهای زیاد.',
        ],
        [
            'id' => 'filter-03',
            'tech' => 'quick-filter',
            'category' => 'filters',
            'name' => 'فیلتر سریع و انتخاب دوره',
            'component' => '<x-filters.quick :options :active>',
            'source' => 'resources/views/components/filters/quick.blade.php',
            'description' => 'ردیف سگمنت‌های تک‌کلیکی (امروز/این هفته/این ماه) که کل query string را حفظ می‌کنند. aria-current برای صفحه‌خوان.',
            'variants' => ['انتخاب دوره', 'دوره مقایسه', 'فیلتر سریع'],
            'usage' => 'برای تغییر سریع بازه بدون باز کردن پنل.',
        ],
        [
            'id' => 'nav-03',
            'tech' => 'tabs',
            'category' => 'navigation',
            'name' => 'تب‌ها',
            'component' => '<x-nav.tabs :tabs param>',
            'source' => 'resources/views/components/nav/tabs.blade.php',
            'description' => 'دو حالت: URL-محور (لینک، قابل اشتراک، سرور-محور) یا Alpine محلی. سرریز افقی در موبایل و aria-selected برای صفحه‌خوان.',
            'variants' => ['URL-محور', 'Alpine محلی', 'با شمارنده'],
            'usage' => 'برای بخش‌های گزارش از حالت URL-محور استفاده کنید تا لینک قابل اشتراک بماند.',
        ],
        [
            'id' => 'nav-04',
            'tech' => 'pagination',
            'category' => 'navigation',
            'name' => 'صفحه‌بندی',
            'component' => '<x-nav.pagination :paginator :perPageUrl>',
            'source' => 'resources/views/components/nav/pagination.blade.php',
            'description' => 'صفحه‌بندی سرور-محور با برچسب فارسی، فلش‌های RTL، شماره صفحات و انتخاب تعداد در صفحه. query stringهای فعال حفظ می‌شوند.',
            'variants' => ['قبلی/بعدی', 'شماره صفحه', 'تعداد در صفحه'],
            'usage' => 'همراه TableQuery استفاده شود تا مرتب‌سازی و فیلتر با تغییر صفحه از بین نرود.',
        ],
        [
            'id' => 'nav-05',
            'tech' => 'section-header',
            'category' => 'navigation',
            'name' => 'سربرگ بخش و گزارش',
            'component' => '<x-nav.section-header title :actions>',
            'source' => 'resources/views/components/nav/section-header.blade.php',
            'description' => 'عنوان + توضیح + نشان وضعیت با اسلات عملیات در سمت مقابل (فیلتر، خروجی، نهایی‌سازی).',
            'variants' => ['سطح صفحه', 'سطح بخش', 'با وضعیت'],
            'usage' => 'بالای هر بخش گزارش.',
        ],
        [
            'id' => 'state-04',
            'tech' => 'data-warning-banners',
            'category' => 'states',
            'name' => 'بنر داده کهنه/ناقص/آفلاین',
            'component' => '<x-states.state variant="stale|partial|offline">',
            'source' => 'resources/views/components/states/state.blade.php',
            'description' => 'این‌ها هشدار روی داده‌ای هستند که همچنان نمایش داده می‌شود، پس به‌شکل بنر رندر می‌شوند نه جایگزین محتوا. آیکن + متن (نه فقط رنگ).',
            'variants' => ['stale', 'partial', 'offline'],
            'usage' => 'وقتی اعداد نمایش داده می‌شوند ولی ممکن است تغییر کنند.',
        ],
    ],
];
